insert into PERSON (ID, FIRST_NAME, LAST_NAME, ADDRESS_ID) values (NEXT VALUE FOR PERSON_ID_SEQ, 'Nicolas','Dupond',1);
insert into PERSON (ID, FIRST_NAME, LAST_NAME, ADDRESS_ID) values (NEXT VALUE FOR PERSON_ID_SEQ, 'Klaus','Unternacht',2);
insert into PERSON (ID, FIRST_NAME, LAST_NAME, ADDRESS_ID) values (NEXT VALUE FOR PERSON_ID_SEQ, 'Shinzo','Abe',3);
